In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/uber.csv")

first 5 rows of the data set

In [4]:
df.head()

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5

number of rows and columns

In [7]:
df.shape

(200000, 9)

what are the columns

In [6]:
df.columns

Index(['Unnamed: 0', 'key', 'fare_amount', 'pickup_datetime',
       'pickup_longitude', 'pickup_latitude', 'dropoff_longitude',
       'dropoff_latitude', 'passenger_count'],
      dtype='object')

give info about the data

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         200000 non-null  int64
 1   key                200000 non-null  object
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  object
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(2), object(2)
memory usage: 13.7+ MB

check for dupilicate values in data set

In [5]:
df.duplicated().sum()

np.int64(0)

# Numerical Features Analysis

We will analyze the target variable (fare_amount) and passenger_count to identify potential data quality issues.

In [10]:
df[['fare_amount','passenger_count']].describe()

         fare_amount  passenger_count
count  200000.000000    200000.000000
mean       11.359955         1.684535
std         9.901776         1.385997
min       -52.000000         0.000000
25%         6.000000         1.000000
50%         8.500000         1.000000
75%        12.500000         2.000000
max       499.000000       208.000000

# Findings

1. Dataset contains 200,000 Uber trips.
2. Target variable is fare_amount.
3. Dataset contains 6 useful predictive features.
4. pickup_datetime is stored as object and needs conversion.
5. dropoff_longitude contains 1 missing value.
6. dropoff_latitude contains 1 missing value.
7. key and Unnamed: 0 appear to be non-predictive columns.
8. Negative fare values exist and must be removed.
9. Passenger count contains invalid values such as 0 and 208.
10. Data cleaning is required before EDA and model building.